name: Build and Deploy
defaults:
  run:
    working-directory: react-bqbl-fe
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run build
        env:
          REACT_APP_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          REACT_APP_AUTH_DOMAIN: bqbl-591f3.firebaseapp.com
          REACT_APP_DATABASE_URL: https://bqbl-591f3.firebaseio.com
          REACT_APP_PROJECT_ID: bqbl-591f3
          REACT_APP_STORAGE_BUCKET: bqbl-591f3.appspot.com
          REACT_APP_MESSAGING_SENDER_ID: 983576610595
          REACT_APP_APP_ID: "1:983576610595:web:252f4ee6b70c8b95"
      - name: Archive Production Artifact
        uses: actions/upload-artifact@master
        with:
          name: dist
          path: react-bqbl-fe/build
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: dist
          path: react-bqbl-fe/build
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
